# FAQ {#sec-faq .unnumbered}

Here are some of the commonly-occurring issues that come up during this course and how to resolve them.

::: {.callout-note collapse="true" icon=false}
### My exported map doesn't look as I expect

When you come to print or export a map from QGIS, the software does not simply send what is visible in the Print Layout to the printer. Instead, QGIS refers to the map item settings to define what is printed and how it should appear. If you made changes to one part of the composition since you last refreshed the screen, the map might not be printed as you expect. Making a layer visible in one map item will automatically make it visible (on printing or refreshing) in another unless you choose to lock the layers.

To make sure that you print or export only what you intend to, for each map item:

1. Compose the map item using the layers you need and their properties as you choose.

2. Check the tickbox `lock layers for map item` which you will find under the `Item Properties` tab.

3. Refresh the screen (`View > Refresh`) to make sure that everything looks as you want it to.

4. Only then should you print or export.
:::

::: {.callout-note collapse="true" icon=false}
### My attributes table doesn't look as I expect

asdf
:::

::: {.callout-note collapse="true" icon=false}
### The "Handle Bad Layers" window appears when I open a project 
* If, when you open an existing project, you are presented with a table saying “Handle Bad Layers”, then your QGIS project cannot connect to some or all of the data layers that you have opened previously. This can happen if you inadvertently move or delete data files that are part of your project. The only way to recover is to put things back as they were, or to re-open the ‘Bad Layers’.

* Another possible cause for ‘Bad Layers’ is that OneDrive or the L:drive did not connect properly to your computer when you logged in, and the best solution is to log out and in again.
:::

::: {.callout-note collapse="true" icon=false}
### I'm getting the error "One or more input features have invalid geometry"

asdf
:::

::: {.callout-note collapse="true" icon=false}
### My 'Processing' menu is missing

* If that doesn’t work, explore the Plugins dialog to make sure that the basic processing tools are ‘activated’ (search on “Processing”)
:::

::: {.callout-note collapse="true" icon=false}
### My work didn't save

asdf
:::

## How can I arrange map items perfectly on the print layout?{#sec-guides}

::: {.callout-note collapse="true" icon=false}
### How can I arrange map items perfectly on the print layout?

Use `Guides`
:::

## How can I make "Fig. 1." bold, keeping the rest of the text normal?{#sec-font}

::: {.callout-note collapse="true" icon=false}
### How can I make "Fig. 1." bold, keeping the rest of the text normal?

Check `Render as HTML` and wrap the target text in <b> and </b> tags. 

<span style="font-family: Cantarell; font-size: 24pt"><b>Fig. 1.</b>&nbsp;Wales principal areas.</span>

:::

::: {.callout-note collapse="true" icon=false}
### One of my panels (Layers, Items, Item Properties) has gone missing, how do I get it back?

View -> relevant panels. Sometimes missing, not on default
:::

